### ISSUE TITLE
Nothing happens - It just doesn't work.

### ISSUE THREAD

**Issue by Supertecnoboff** [chrhansen/simple-oauth1#12]
I am trying to authenticate the user, the login web view controller appears, it remains blank and nothing happens after that. After putting an NSLog statement in the ```loginWithWebView``` method, it appears that the said method will not run - the NSLog is not printed. I am using the following code:

```

// Set the various OAuth 1.0a settings.
self.oauth1Controller.pass_oauth_callback = auth_data[0];
self.oauth1Controller.pass_consumer_key = auth_data[1]; 
self.oauth1Controller.pass_consumer_secret = auth_data[2];    
self.oauth1Controller.pass_auth_url = auth_data[3];
self.oauth1Controller.pass_request_token_url = auth_data[4];
self.oauth1Controller.pass_authenticate_url = auth_data[5];
self.oauth1Controller.pass_access_token_url = auth_data[6];
self.oauth1Controller.pass_api_url = auth_data[7];
self.oauth1Controller.pass_oauth_scope_params = auth_data[8];

// Setup the OAuth 1.0a login view.
UIStoryboard *story_file = [UIStoryboard storyboardWithName:@"LoginWebViewController" bundle:nil];
LoginWebViewController *login_view = [story_file instantiateViewControllerWithIdentifier:@"loginOA1"];
    
    // Open the OAuth 1.0a login view.
    [self presentViewController:login_view animated:YES completion:^{
        
        NSLog(@"TESTING: %@", self.oauth1Controller.pass_api_url);
        
        // Begin the OAuth 1.0a authentication process.
        [self.oauth1Controller loginWithWebView:login_view.webView completion:^(NSDictionary *oauthTokens, NSError *error) {
            
            if (!error) {
                NSLog(@"Success: %@", oauthTokens);
            }
            
            else {
                NSLog(@"Error authenticating: %@", error.localizedDescription);
            }
            
            // Now close OAuth 1.0a login view.
            [self dismissViewControllerAnimated:YES completion: ^{
                self.oauth1Controller = nil;
            }];
        }];
    }];
```

**Note**
I added the following properties to the OAuth1Controller class, so that I can pass in the OAuth API links/settings (because I am allowing the user to login via a few different services, so I don't want to just ```#define``` everything in that class).

```
// Properties - strings, URLs, etc..
@property (nonatomic, retain) NSString *pass_oauth_callback;
@property (nonatomic, retain) NSString *pass_consumer_key;
@property (nonatomic, retain) NSString *pass_consumer_secret;
@property (nonatomic, retain) NSString *pass_auth_url;
@property (nonatomic, retain) NSString *pass_request_token_url;
@property (nonatomic, retain) NSString *pass_authenticate_url;
@property (nonatomic, retain) NSString *pass_access_token_url;
@property (nonatomic, retain) NSString *pass_api_url;
@property (nonatomic, retain) NSString *pass_oauth_scope_params;
```

**Comment by chrhansen** [comment]
Hi @Supertecnoboff thanks for the feedback. This library is bit out of date. OAuth 1.0a was an update to OAuth 1.0 to mitigate some vulnerabilities in the protocol, but since then most serious services have moved to OAuth 2.0, including LinkedIn: https://developer.linkedin.com/docs/oauth2#

If you still want to authenticate against an OAuth 1.0a-service, that should still be possible with this library. It was implemented for iOS6 so probably some of the view-controller/app-delegate/etc. callbacks have changed since then.

**Comment by Supertecnoboff** [comment]
@chrhansen Yes I am well aware that most reputable services use OAuth 2.0. I take no joy in having to look through OAuth 1.0a, as its a complete nightmare to work on.... but... I am trying to use both the Tumblr and Flickr API's, they both use OAuth 1.0a.

I have tried many different libraries, most are either: full of deprecated code, don't work, dependent on a million different libraries or just flat out crap.

Do you have any suggestion as to where I could find a good up to date (or fairly up to date) OAuth 1.0a library for iOS?

**Comment by chrhansen** [comment]
@Supertecnoboff I'm doing mostly web and security engineering these days. But could you setup a test repo (iOS 10) and link it here so that I can easily reproduce your error? Then I'd be happy to take a look and fix bugs in this repo.

There might be other developers like you, who are trying to communicate with slightly out-of-date OAuth APIs.

**Comment by Supertecnoboff** [comment]
@chrhansen You are the best, thank you! I setup a simple demo Single View Application and upload it to a new repo/link it here. Just give me a few mins :) 

Although I should state, I have not been able to find out an error code as such, more an area of code that doesn't run. (Via basic NSLog testing....lol)

**Comment by chrhansen** [comment]
Well, I'm only promising to have a look for now :)

**Comment by Supertecnoboff** [comment]
@chrhansen  Sure no worries, I appreciate any help I can get, thank you in advance. Here is the git repo with the super simple Xcode project: [Simple-OAuth-1.0a---iOS](https://github.com/Supertecnoboff/Simple-OAuth-1.0a---iOS)

**Comment by chrhansen** [comment]
@Supertecnoboff I had a look at your example project, and I noted that `self.oauth1Controller` was `nil`, which reminded me of Objective-C where messages to `nil` are perfectly fine.

Anyway, add this in the implementation of `ViewController.m`:

```objc
- (OAuth1Controller *)oauth1Controller
{
    if (_oauth1Controller == nil) {
        _oauth1Controller = [[OAuth1Controller alloc] init];
    }
    return _oauth1Controller;
}
```

But I'd actually recommend you to first make the Oauth1 authentication work with this example project, before moving the necessary pieces over to your project as it can be quite a pain to debug, whether you forgot something simple as this or a trailing space somewhere results in the wrong HMAC-signature.

Starring at my code from 2012 I must admit that `OAuth1Controller` could be implemented a lot cleaner. I also remember how various oauth providers would have slightly different implementations of the standard and that LinkedIn, at the time, followed the Oauth1-standard most strict of the handful of providers I tried, why I used them as an example.

**Comment by Supertecnoboff** [comment]
@chrhansen Thanks for your help! In the end there were three main issues that needed fixing to get this library to work:

1) I implemented your code which got the ```loginWithWebView``` and all other subsequent methods working.

2) I noticed that your library was using some old deprecated synchronous blocking network method.... so I replaced them with much better modern day asynchronous```dataTaskWithRequest``` methods. It has its own block, its asynchronous, its cleaner, easier to use and better in every single way known to man..... anyway.... I forgot to add the little ```}] resume]``` part of the method block. I didn't realise that ```NSURLSession``` are suspended by default, thus why two of your methods were not returning their completion blocks.

3) Finally there was one last thing to fix, the ```obtainRequestTokenWithCompletion``` method. I tested and compared the request URL and header that it generates to that of another partially working OAuth 1.0a library called [TDOAuth](https://github.com/tweetdeck-archive/TDOAuth).

I found that the [TDOAuth](https://github.com/tweetdeck-archive/TDOAuth) library creates its ```NSURLRequest``` slightly differently to that of your library. Long story short, the request header (or whatever) that your library creates is in some way invalid/out of date and is rejected by many different APIs that I have tested. This leads to your library being unable to retrieve a ```request_token```.

So I am using [TDOAuth](https://github.com/tweetdeck-archive/TDOAuth) to create the request for that one method. From therein everything works and I receive an access token. The reason I am not just using [TDOAuth](https://github.com/tweetdeck-archive/TDOAuth) instead, is because it works in terms of creating/sending request/etc.... but..... I can't get it to retrieve a ```oauth_verifier``` token and nor can I get it to close the web view when the user is finished with authentication.

This is your new ```obtainRequestTokenWithCompletion``` method:


```
-(void)obtainRequestTokenWithCompletion:(void (^)(NSError *error, NSDictionary *responseParams))completion {
  
    NSMutableDictionary *dict = [NSMutableDictionary dictionary];
    [dict setObject:pass_oauth_callback forKey:@"oauth_callback"];
    
    //init request
    NSURLRequest *request = [TDOAuth URLRequestForPath:pass_request_token_url GETParameters:dict scheme:@"https" host:pass_api_url consumerKey:pass_consumer_key consumerSecret:pass_consumer_secret accessToken:nil tokenSecret:nil];
    
    // Setup the network request.
    NSURLSession *session = [NSURLSession sharedSession];
    
    // Perform the network request.
    [[session dataTaskWithRequest:request completionHandler:^(NSData * _Nullable data, NSURLResponse * _Nullable response, NSError * _Nullable error) {
        
        NSString *reponseString = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
        
        if (error != nil) {
            NSLog(@"obtainRequestTokenWithCompletion ERROR: %@", error);
        }
        
        completion(nil, CHParametersFromQueryString(reponseString));
    }] resume];
}
```

If you are interested in seeing the full working project (with your non working code commented out), I have updated my repo: [Simple-OAuth-1.0a---iOS](https://github.com/Supertecnoboff/Simple-OAuth-1.0a---iOS)

**Comment by chrhansen** [comment]
@Supertecnoboff Good you got it working, and yeah, it's 5 years since I built this library, so it's likely out of date on several fronts. If the above is a drop-in replacement for `obtainRequestTokenWithCompletion:` feel free to submit a pull request. 

I'll have a look at your project too.
